name: Deploy Node.js app to Azure Web App (second)

on:
  push:
    branches:
      - firstlocal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: second
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SECOND }}
          package: .
